CREATE TABLE [dbo].[UsuarioActivacion](
	[UsuarioID] [int] NOT NULL,
	[CodigoActivacion] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_UsuarioActivacion] PRIMARY KEY CLUSTERED 
(
	[UsuarioID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]